"""add polling interval to github config

Revision ID: 028dfd4ebae4
Revises: 0748895fb1d0
Create Date: 2025-08-10 15:00:12.528457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028dfd4ebae4'
down_revision: Union[str, None] = '0748895fb1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_config', sa.Column('polling_interval_minutes', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_config', 'polling_interval_minutes')
    # ### end Alembic commands ###
