"""merge branches permanently

Revision ID: 0748895fb1d0
Revises: 0345ee076894, 57bf83b11bfb, add_admin_fields_to_users, protocol_client_assoc
Create Date: 2025-08-10 14:59:53.735089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0748895fb1d0'
down_revision: Union[str, None] = ('0345ee076894', '57bf83b11bfb', 'add_admin_fields_to_users', 'protocol_client_assoc')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###