"""add bpm

Revision ID: 25eecb29f0f2
Revises: e6779f9fe334
Create Date: 2024-06-18 13:14:46.555434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25eecb29f0f2'
down_revision: Union[str, None] = 'e6779f9fe334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('bpm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'bpm')
    # ### end Alembic commands ###
