"""add network

Revision ID: 2f342f47aceb
Revises: 25eecb29f0f2
Create Date: 2024-06-18 13:27:03.350616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f342f47aceb'
down_revision: Union[str, None] = '25eecb29f0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('network', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'network')
    # ### end Alembic commands ###
