"""move_user_models_to_api

Revision ID: 38796cceb6bf
Revises: ff17be643d4b
Create Date: 2024-11-16 07:19:46.807231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38796cceb6bf'
down_revision: Union[str, None] = 'ff17be643d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.LargeBinary(), nullable=True))
    op.add_column('Users', sa.Column('oauth_github', sa.String(length=100), nullable=True))
    op.add_column('Users', sa.Column('oauth_google', sa.String(length=100), nullable=True))
    op.add_column('Users', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('Users', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('Users', sa.Column('picture', sa.String(length=100), nullable=True))
    op.alter_column('Users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index('ix_Users_id', table_name='Users')
    op.create_unique_constraint(None, 'Users', ['email'])
    op.create_unique_constraint(None, 'Users', ['username'])
    op.drop_column('Users', 'full_name')
    op.drop_column('Users', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Users', type_='unique')
    op.create_index('ix_Users_id', 'Users', ['id'], unique=False)
    op.alter_column('Users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('Users', 'picture')
    op.drop_column('Users', 'last_name')
    op.drop_column('Users', 'first_name')
    op.drop_column('Users', 'oauth_google')
    op.drop_column('Users', 'oauth_github')
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###
