"""increase_picture_column_length

Revision ID: 3d73e28bfa58
Revises: 38796cceb6bf
Create Date: 2024-11-16 07:22:29.346926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d73e28bfa58'
down_revision: Union[str, None] = '38796cceb6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'picture',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'picture',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
