"""add github_url for protocol_updates

Revision ID: 7d458792c2c0
Revises: 2f342f47aceb
Create Date: 2024-06-18 15:09:50.109503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d458792c2c0'
down_revision: Union[str, None] = '2f342f47aceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocol_tracking', sa.Column('github_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocol_tracking', 'github_url')
    # ### end Alembic commands ###
