"""add is_closed column

Revision ID: 98582cbf0ba4
Revises: e94db952d03f
Create Date: 2024-06-24 08:11:02.477620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98582cbf0ba4'
down_revision: Union[str, None] = 'e94db952d03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocol_tracking', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.drop_index('ix_protocols_name', table_name='protocols')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_protocols_name', 'protocols', ['name'], unique=False)
    op.drop_column('protocol_tracking', 'is_closed')
    # ### end Alembic commands ###
