"""Add multiple snapshot prefixes support

Revision ID: 9af7276ce3b2
Revises: b2c3d4e5f6a7
Create Date: 2025-09-01 20:46:10.288183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af7276ce3b2'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_indices', sa.Column('prefix_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'snapshot_indices', 'protocol_snapshot_prefixes', ['prefix_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snapshot_indices', type_='foreignkey')
    op.drop_column('snapshot_indices', 'prefix_id')
    # ### end Alembic commands ###
