"""Setup

Revision ID: a6baeefb782a
Revises: 
Create Date: 2024-06-18 10:55:31.413915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6baeefb782a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_prerelease', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('release_name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('tarball', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('ticket', sa.String(), nullable=True),
    sa.Column('hard_fork', sa.Boolean(), nullable=True),
    sa.Column('fork_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('protocols', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('protocols', sa.Column('explorer', sa.String(), nullable=True))
    op.add_column('protocols', sa.Column('public_rpc', sa.String(), nullable=True))
    op.create_index(op.f('ix_protocols_id'), 'protocols', ['id'], unique=False)
    op.drop_column('protocols', 'org')
    op.drop_column('protocols', 'repo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('repo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('protocols', sa.Column('org', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_protocols_id'), table_name='protocols')
    op.drop_column('protocols', 'public_rpc')
    op.drop_column('protocols', 'explorer')
    op.drop_column('protocols', 'github_url')
    op.drop_table('protocol_tracking')
    # ### end Alembic commands ###
