"""Add multiple notification URLs and Telegram support

Revision ID: add_multiple_notification_urls
Revises: 0748895fb1d0
Create Date: 2025-08-14 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_multiple_notification_urls'
down_revision = '0748895fb1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to notification_config table
    op.add_column('notification_config', sa.Column('discord_webhook_urls', sa.JSON(), nullable=True))
    op.add_column('notification_config', sa.Column('slack_webhook_urls', sa.JSON(), nullable=True))
    op.add_column('notification_config', sa.Column('telegram_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('notification_config', sa.Column('telegram_bot_token', sa.String(), nullable=True))
    op.add_column('notification_config', sa.Column('telegram_chat_ids', sa.JSON(), nullable=True))
    op.add_column('notification_config', sa.Column('generic_webhook_urls', sa.JSON(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove added columns
    op.drop_column('notification_config', 'generic_webhook_urls')
    op.drop_column('notification_config', 'telegram_chat_ids')
    op.drop_column('notification_config', 'telegram_bot_token')
    op.drop_column('notification_config', 'telegram_enabled')
    op.drop_column('notification_config', 'slack_webhook_urls')
    op.drop_column('notification_config', 'discord_webhook_urls')
    
    # ### end Alembic commands ###