"""add proto_family

Revision ID: e6779f9fe334
Revises: a6baeefb782a
Create Date: 2024-06-18 12:43:19.096597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6779f9fe334'
down_revision: Union[str, None] = 'a6baeefb782a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('proto_family', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocols', 'proto_family')
    # ### end Alembic commands ###
